/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbcexamples;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 *
 * @author CLASSROOM01
 */
public class DataEntry extends java.awt.Frame {

    /**
     * Creates new form DataEntry
     */
    public DataEntry() {
        initComponents();
        setSize(400,400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        t1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        t2 = new java.awt.TextField();
        label3 = new java.awt.Label();
        t3 = new java.awt.TextField();
        button1 = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setText("Rollno");
        add(label1);
        label1.setBounds(80, 50, 40, 20);
        add(t1);
        t1.setBounds(190, 50, 80, 20);

        label2.setText("Name");
        add(label2);
        label2.setBounds(80, 100, 38, 20);
        add(t2);
        t2.setBounds(190, 100, 80, 20);

        label3.setText("Marks");
        add(label3);
        label3.setBounds(80, 150, 37, 20);
        add(t3);
        t3.setBounds(190, 150, 80, 20);

        button1.setLabel("Save");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(130, 220, 43, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        String s1=t1.getText();
        String s2=t2.getText();
        String s3=t3.getText();
        String qr="insert into stud values("+s1+",'"+s2+"',"+s3+")";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/data11", "root", "root");
            Statement stmt=con.createStatement();
            int n=stmt.executeUpdate(qr);
            setTitle(n+" row added");
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t1.requestFocus();
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataEntry().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField t1;
    private java.awt.TextField t2;
    private java.awt.TextField t3;
    // End of variables declaration//GEN-END:variables
}
